### ISSUE TITLE
Remove RLock exception that occurs when running on python 3.9 and later.

### ISSUE THREAD

**Issue by andershenja** [baltrad/rave#64]
When running for example

%> /usr/lib/rave/bin/odc_toolbox -i input -o output -q beamb

using python3.10 the following exception occurs:

Exception ignored in: <function _after_at_fork_child_reinit_locks at 0x78f1e38eef80>
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 256, in _after_at_fork_child_reinit_locks
    handler._at_fork_reinit()
  File "/usr/lib/python3.10/logging/__init__.py", line 910, in _at_fork_reinit
    self.lock._at_fork_reinit()
AttributeError: 'RLock' object has no attribute '_at_fork_reinit'

**Comment by andershenja** [comment]
Seems like they have corrected an issue with deadlocks that occurs when using logging and multiprocessing that was corrected in 3.9 or something similar. For example https://github.com/python/cpython/commit/4c3da783cffb8471303fbae3e09f3d67b31c3d06

So, a solution that probably work is just to change the code in rave_pgf_logger.py#init_loghandler to say:
        if sys.version_info.major > 3 or (sys.version_info.major == 3 and sys.version_info.minor < 9):
            handler.lock = multiprocessing.RLock()

**Comment by andershenja** [comment]
Solved in rave-build-91
